const BOUNDS={minX:27,maxX:76,minY:46,maxY:74};
// Approximate walk-floor furniture footprints in percentage coordinates.
// When real house objects are loaded these can later be extended from position_data.
const OBSTACLES=[{x1:31,x2:43,y1:48,y2:59},{x1:44,x2:58,y1:54,y2:62},{x1:62,x2:76,y1:46,y2:58},{x1:48,x2:63,y1:68,y2:75}];
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const inObstacle=(x,y,margin=1.5)=>OBSTACLES.some(box=>x>box.x1-margin&&x<box.x2+margin&&y>box.y1-margin&&y<box.y2+margin);
export function nearestSafePoint(x,y){x=clamp(x,BOUNDS.minX,BOUNDS.maxX);y=clamp(y,BOUNDS.minY,BOUNDS.maxY);if(!inObstacle(x,y))return{x,y};for(let radius=2;radius<=24;radius+=2){for(let angle=0;angle<Math.PI*2;angle+=Math.PI/12){const candidate={x:clamp(x+Math.cos(angle)*radius,BOUNDS.minX,BOUNDS.maxX),y:clamp(y+Math.sin(angle)*radius,BOUNDS.minY,BOUNDS.maxY)};if(!inObstacle(candidate.x,candidate.y))return candidate}}return{x:BOUNDS.minX,y:BOUNDS.maxY}}
export class CatMover{
 constructor(el,index,peers){this.el=el;this.index=index;this.peers=peers;this.pos=nearestSafePoint(40+index*8,57+(index%2)*6);this.target={...this.pos};this.velocity={x:0,y:0};this.speed=0;this.dir=1;this.pendingDir=1;this.turning=false;this.frame=0;this.lastFrame=0;this.last=performance.now();this.nextWander=this.last+8000+Math.random()*10000;this.nextBlink=this.last+1800+Math.random()*3500;this.userCommand=false;this.running=true;requestAnimationFrame(t=>this.tick(t))}
 setTarget(x,y,{user=false}={}){this.target=nearestSafePoint(x,y);this.userCommand=user;const desired=this.target.x<this.pos.x?-1:1;if(desired!==this.dir&&this.speed>.8){this.pendingDir=desired;this.turning=true}else this.dir=desired;this.el.classList.remove('idle')}
 obstacleForce(){let fx=0,fy=0;for(const other of this.peers()){if(other===this)continue;const dx=this.pos.x-other.pos.x,dy=this.pos.y-other.pos.y,d=Math.hypot(dx,dy);if(d<7&&d>.01){const push=(7-d)*1.4;fx+=dx/d*push;fy+=dy/d*push}}for(const box of OBSTACLES){const nearX=clamp(this.pos.x,box.x1-2.5,box.x2+2.5),nearY=clamp(this.pos.y,box.y1-2,box.y2+2),dx=this.pos.x-nearX,dy=this.pos.y-nearY,d=Math.hypot(dx,dy);if(d<4){if(d>.01){fx+=dx/d*(4-d)*2;fy+=dy/d*(4-d)*2}else{const sides=[{x:box.x1-this.pos.x,y:0},{x:box.x2-this.pos.x,y:0},{x:0,y:box.y1-this.pos.y},{x:0,y:box.y2-this.pos.y}].sort((a,b)=>Math.hypot(a.x,a.y)-Math.hypot(b.x,b.y));fx+=sides[0].x*2;fy+=sides[0].y*2}}}return{x:fx,y:fy}}
 tick(now){if(!this.running)return;const dt=Math.min(45,now-this.last)/1000;this.last=now;let dx=this.target.x-this.pos.x,dy=this.target.y-this.pos.y,d=Math.hypot(dx,dy);if(this.turning){this.speed=Math.max(0,this.speed-24*dt);if(this.speed<.35){this.dir=this.pendingDir;this.turning=false}}else if(d>.35){const cruise=Math.min(12,4+d*.7);this.speed=Math.min(cruise,this.speed+18*dt)}else this.speed=Math.max(0,this.speed-22*dt);
  if(d>.08&&this.speed>.05){const avoid=this.obstacleForce();let nx=dx/d+avoid.x*.08,ny=dy/d+avoid.y*.08;const norm=Math.hypot(nx,ny)||1;nx/=norm;ny/=norm;this.velocity.x+=(nx*this.speed-this.velocity.x)*Math.min(1,dt*7);this.velocity.y+=(ny*this.speed-this.velocity.y)*Math.min(1,dt*7);this.pos.x=clamp(this.pos.x+this.velocity.x*dt,BOUNDS.minX,BOUNDS.maxX);this.pos.y=clamp(this.pos.y+this.velocity.y*dt,BOUNDS.minY,BOUNDS.maxY)}
  if(d<.35&&this.speed<.4){this.speed=0;this.velocity={x:0,y:0};this.el.classList.add('idle');if(this.userCommand){this.userCommand=false;this.nextWander=now+8000+Math.random()*10000}else if(now>this.nextWander){if(Math.random()<.3){this.nextWander=now+8000+Math.random()*10000}else{const angle=Math.random()*Math.PI*2,distance=5+Math.random()*11;this.setTarget(this.pos.x+Math.cos(angle)*distance,this.pos.y+Math.sin(angle)*distance);this.nextWander=now+8000+Math.random()*10000}}}
  if(this.speed>.7&&now-this.lastFrame>Math.max(80,150-this.speed*4)){this.frame=(this.frame+1)%5;this.el.style.backgroundPosition=`${this.frame*25}% 0`;this.lastFrame=now}else if(this.speed<=.7)this.el.style.backgroundPosition='0 0';
  if(now>this.nextBlink){this.el.classList.add('blink');setTimeout(()=>this.el.classList.remove('blink'),130);this.nextBlink=now+2200+Math.random()*4500}
  const depth=.82+((this.pos.y-BOUNDS.minY)/(BOUNDS.maxY-BOUNDS.minY))*.3;this.el.style.left=this.pos.x+'%';this.el.style.top=this.pos.y+'%';this.el.style.transform=`translate(-50%,-72%) scale(${this.dir},${depth})`;this.el.style.zIndex=String(10+Math.round(this.pos.y));requestAnimationFrame(t=>this.tick(t))}
 destroy(){this.running=false;this.el.remove()}
}
