import{state,setUser}from'./state.js';import{api}from'./api.js';import{renderCats}from'./cat.js';
const $=s=>document.querySelector(s),toast=$('#toast'),log=$('#debugLog');let timer;
function message(text){clearTimeout(timer);toast.textContent=text;toast.classList.add('show');timer=setTimeout(()=>toast.classList.remove('show'),1500)}function debug(text){log.textContent=`${new Date().toLocaleTimeString()} ${text}\n`+log.textContent}
function go(id){if(!document.getElementById(id))id='home';document.querySelectorAll('.screen').forEach(s=>s.classList.toggle('active',s.id===id));history.replaceState(null,'','#'+id);if(id==='shop')loadItems();if(id==='house'&&state.userId)loadHouse()}
async function connect(){setUser($('#apiBase').value,$('#userId').value);if(!state.userId){state.cats=[{user_cat_id:'local-starter',cat_id:1,name:'주황 고양이',rarity:'STARTER'}];renderCats(state.cats);debug('로컬 스타터 모드');return}try{await api.starter(state.userId);state.cats=await api.cats(state.userId);const user=await api.user(state.userId);$('#balance').textContent=Number(user.balance).toLocaleString();renderCats(state.cats);debug(`DB 고양이 ${state.cats.length}마리 로드`);message('사용자 고양이를 불러왔어요')}catch(e){debug('연결 실패: '+e.message);message('연결 실패 · Debug를 확인하세요')}}
async function loadTasks(){try{state.tasks=await api.tasks();const select=$('#taskSelect');select.innerHTML=state.tasks.map(t=>`<option value="${t.id}">${t.type} · 난이도 ${t.difficulty}</option>`).join('')||'<option>활성 문제가 없습니다</option>';if(state.tasks[0]){$('#codeEditor').value=state.tasks[0].template_code||'';$('#taskInfo').textContent=`task_id ${state.tasks[0].id}`}debug(`GET /tasks · ${state.tasks.length}개`)}catch(e){message('문제 조회 실패');debug(e.message)}}
async function submit(){if(!state.userId)return message('Debug에서 사용자 UUID를 먼저 연결하세요');const task_id=$('#taskSelect').value;if(!task_id)return message('문제를 먼저 불러오세요');try{const result=await api.submitAttempt({user_id:state.userId,task_id,submitted_code:$('#codeEditor').value,used_hint:false});$('#attemptState').textContent=`${result.status} · attempt ${result.attempt_id}`;debug(`POST /attempts · ${result.status}`)}catch(e){message('제출 실패');debug(e.message)}}
async function loadItems(){try{const items=await api.items();$('#shopItems').innerHTML=items.map(i=>`<article class="item"><small class="surface">${i.category}</small><b>${i.name}</b><span>🪙 ${Number(i.price).toLocaleString()}</span><button class="primary" data-buy="${i.id}">구매</button></article>`).join('')||'<p>등록된 상품이 없습니다.</p>';debug(`GET /items · ${items.length}개`)}catch(e){$('#shopItems').innerHTML='<p>FastAPI를 실행하면 실제 상품이 표시됩니다.</p>';debug(e.message)}}
async function buy(itemId){if(!state.userId)return message('구매하려면 사용자 UUID를 연결하세요');try{const r=await api.buy(state.userId,Number(itemId));$('#balance').textContent=Number(r.current_balance).toLocaleString();message(`${r.item_name} 구매 완료`);debug(`POST /shop/buy · item ${itemId}`)}catch(e){message('구매 실패: '+e.message);debug(e.message)}}
async function loadHouse(){if(!state.userId)return message('로컬 모드에서는 기본 하우스를 사용합니다');try{state.house=await api.house(state.userId);$('#houseStatus').textContent=`하우스 Lv.${state.house.house_level} · 배치 ${state.house.placed_objects.length}개`;$('#placedItems').innerHTML=state.house.placed_objects.map(o=>`<div class="placed">${o.name} <small>${JSON.stringify(o.position_data)}</small></div>`).join('')||'<p>배치된 가구가 없습니다.</p>';debug('GET /users/{id}/house')}catch(e){message('하우스 조회 실패');debug(e.message)}}
document.addEventListener('click',e=>{const nav=e.target.closest('[data-go]');if(nav)return go(nav.dataset.go);const demo=e.target.closest('[data-demo]');if(demo)return message('DEMO 흐름입니다 · 실제 재화는 변하지 않아요');const product=e.target.closest('[data-buy]');if(product)buy(product.dataset.buy)});addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('#debugPanel').open)go('home')});$('#debugToggle').onclick=()=>$('#debugPanel').showModal();$('#connectUser').onclick=connect;$('#disconnectUser').onclick=()=>{$('#userId').value='';connect()};$('#loadTasks').onclick=loadTasks;$('#submitAttempt').onclick=submit;$('#loadItems').onclick=loadItems;$('#loadHouse').onclick=loadHouse;$('#apiBase').value=state.apiBase;$('#userId').value=state.userId;$('#taskSelect').onchange=()=>{const task=state.tasks.find(t=>t.id===$('#taskSelect').value);if(task)$('#codeEditor').value=task.template_code||''};renderCats(state.cats);if(state.userId)connect();const hash=location.hash.slice(1);if(hash)go(hash);
