"""add task attempt context

Revision ID: 3c63b197cf85
Revises: 20260827_0001
Create Date: 2026-08-30 18:11:03.828137
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3c63b197cf85'
down_revision: Union[str, Sequence[str], None] = '20260827_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_attempts', sa.Column('context_type', sa.String(), nullable=False))
    op.add_column('task_attempts', sa.Column('attendance_id', sa.UUID(), nullable=True))
    op.add_column('task_attempts', sa.Column('room_task_id', sa.UUID(), nullable=True))
    op.add_column('task_attempts', sa.Column('rank_challenge_task_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'task_attempts', 'attendances', ['attendance_id'], ['id'])
    op.create_foreign_key(None, 'task_attempts', 'rank_challenge_tasks', ['rank_challenge_task_id'], ['id'])
    op.create_foreign_key(None, 'task_attempts', 'room_tasks', ['room_task_id'], ['id'])
    op.create_check_constraint('ck_task_attempts_context', 'task_attempts', "\n            (\n                context_type = 'LEARNING'\n                AND attendance_id IS NULL\n                AND room_task_id IS NULL\n                AND rank_challenge_task_id IS NULL\n            )\n            OR\n            (\n                context_type = 'DAILY'\n                AND attendance_id IS NOT NULL\n                AND room_task_id IS NULL\n                AND rank_challenge_task_id IS NULL\n            )\n            OR\n            (\n                context_type = 'BATTLE'\n                AND attendance_id IS NULL\n                AND room_task_id IS NOT NULL\n                AND rank_challenge_task_id IS NULL\n            )\n            OR\n            (\n                context_type = 'RANKING'\n                AND attendance_id IS NULL\n                AND room_task_id IS NULL\n                AND rank_challenge_task_id IS NOT NULL\n            )\n            ")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_task_attempts_context', 'task_attempts', type_='check')
    op.drop_constraint(None, 'task_attempts', type_='foreignkey')
    op.drop_constraint(None, 'task_attempts', type_='foreignkey')
    op.drop_constraint(None, 'task_attempts', type_='foreignkey')
    op.drop_column('task_attempts', 'rank_challenge_task_id')
    op.drop_column('task_attempts', 'room_task_id')
    op.drop_column('task_attempts', 'attendance_id')
    op.drop_column('task_attempts', 'context_type')
    # ### end Alembic commands ###
